export const CEFR_GUIDELINES = {
    A1: {
        grammar: [
            { topic: "Present Simple - Verb 'to be' (Positive Forms)", order: 1 },
            { topic: "Present Simple - Verb 'to be' (Negative Forms)", order: 2 },
            { topic: "Present Simple - Verb 'to be' (Questions)", order: 3 },
            { topic: "Personal Pronouns (Subject)", order: 4 },
            { topic: "Personal Pronouns (Object)", order: 5 },
            { topic: "Possessive Adjectives", order: 6 },
            { topic: "Possessive 's", order: 7 },
            { topic: "Indefinite Articles (a/an)", order: 8 },
            { topic: "Definite Article (the)", order: 9 },
            { topic: "Demonstratives (this/that/these/those)", order: 10 },
            { topic: "Question Words (what, where, when)", order: 11 },
            { topic: "Question Words (who, how, why)", order: 12 },
            { topic: "Plural Nouns (Regular)", order: 13 },
            { topic: "Plural Nouns (Irregular)", order: 14 },
            { topic: "There is/There are (Positive)", order: 15 },
            { topic: "There is/There are (Negative and Questions)", order: 16 },
            { topic: "Can/Can't for Ability", order: 17 },
            { topic: "Can for Permission and Requests", order: 18 },
            { topic: "Prepositions of Place (in, on, under, next to)", order: 19 },
            { topic: "Prepositions of Time (in, on, at)", order: 20 },
            { topic: "Present Simple (Positive) - Regular Verbs", order: 21 },
            { topic: "Present Simple (Negative) - Regular Verbs", order: 22 },
            { topic: "Present Simple (Questions) - Regular Verbs", order: 23 },
            { topic: "Adverbs of Frequency", order: 24 },
            { topic: "Imperative Forms", order: 25 },
            { topic: "Like/Love/Hate + Noun", order: 26 },
            { topic: "Telling the Time", order: 27 },
            { topic: "Basic Conjunctions (and, but, or)", order: 28 },
            { topic: "Subject-Verb Agreement", order: 29 },
            { topic: "Have got/Has got", order: 30 }
        ],
        vocabulary: [
            { topic: "Numbers 1-20", order: 1, wordCount: 20 },
            { topic: "Numbers 21-100", order: 2, wordCount: 20 },
            { topic: "Colors", order: 3, wordCount: 12 },
            { topic: "Days of the Week", order: 4, wordCount: 7 },
            { topic: "Months and Seasons", order: 5, wordCount: 16 },
            { topic: "Immediate Family Members", order: 6, wordCount: 10 },
            { topic: "Extended Family Members", order: 7, wordCount: 10 },
            { topic: "Classroom Objects", order: 8, wordCount: 15 },
            { topic: "Personal Items", order: 9, wordCount: 15 },
            { topic: "Basic Adjectives (Descriptions)", order: 10, wordCount: 15 },
            { topic: "Basic Adjectives (Feelings)", order: 11, wordCount: 10 },
            { topic: "Common Countries", order: 12, wordCount: 15 },
            { topic: "Nationalities", order: 13, wordCount: 15 },
            { topic: "Common Jobs and Occupations", order: 14, wordCount: 15 },
            { topic: "Morning Routine Activities", order: 15, wordCount: 10 },
            { topic: "Evening Routine Activities", order: 16, wordCount: 10 },
            { topic: "Basic Action Verbs", order: 17, wordCount: 20 },
            { topic: "Food - Fruits and Vegetables", order: 18, wordCount: 15 },
            { topic: "Food - Basic Items", order: 19, wordCount: 15 },
            { topic: "Drinks", order: 20, wordCount: 10 },
            { topic: "Parts of the House", order: 21, wordCount: 10 },
            { topic: "Furniture", order: 22, wordCount: 15 },
            { topic: "Animals - Pets", order: 23, wordCount: 10 },
            { topic: "Animals - Farm and Wild", order: 24, wordCount: 15 },
            { topic: "Clothes - Basic Items", order: 25, wordCount: 15 },
            { topic: "Weather Expressions", order: 26, wordCount: 10 },
            { topic: "Basic Transportation", order: 27, wordCount: 10 },
            { topic: "Places in Town", order: 28, wordCount: 15 },
            { topic: "Greetings and Farewells", order: 29, wordCount: 10 },
            { topic: "Basic Phrases for Communication", order: 30, wordCount: 15 }
        ],
        A2: {
            grammar: [
                { topic: "Present Simple (Review and Extension)", order: 1 },
                { topic: "Present Continuous (Positive Forms)", order: 2 },
                { topic: "Present Continuous (Negative Forms)", order: 3 },
                { topic: "Present Continuous (Questions)", order: 4 },
                { topic: "Present Simple vs. Present Continuous", order: 5 },
                { topic: "State Verbs vs. Action Verbs", order: 6 },
                { topic: "Past Simple - Verb 'to be'", order: 7 },
                { topic: "Past Simple - Regular Verbs (Positive)", order: 8 },
                { topic: "Past Simple - Regular Verbs (Negative and Questions)", order: 9 },
                { topic: "Past Simple - Common Irregular Verbs (Group 1)", order: 10 },
                { topic: "Past Simple - Common Irregular Verbs (Group 2)", order: 11 },
                { topic: "Past Simple - Time Expressions", order: 12 },
                { topic: "Countable Nouns", order: 13 },
                { topic: "Uncountable Nouns", order: 14 },
                { topic: "Some and Any", order: 15 },
                { topic: "Much, Many, a Lot of", order: 16 },
                { topic: "A Few, A Little", order: 17 },
                { topic: "Comparative Adjectives (Short Adjectives)", order: 18 },
                { topic: "Comparative Adjectives (Long Adjectives)", order: 19 },
                { topic: "Superlative Adjectives (Short Adjectives)", order: 20 },
                { topic: "Superlative Adjectives (Long Adjectives)", order: 21 },
                { topic: "Going to Future (Plans and Intentions)", order: 22 },
                { topic: "Going to Future (Predictions)", order: 23 },
                { topic: "Present Continuous for Future Arrangements", order: 24 },
                { topic: "Adverbs of Manner", order: 25 },
                { topic: "Possessive Pronouns", order: 26 },
                { topic: "Prepositions of Movement", order: 27 },
                { topic: "Verb + Infinitive", order: 28 },
                { topic: "Verb + -ing", order: 29 },
                { topic: "Would Like (Requests and Offers)", order: 30 },
                { topic: "Too and Enough", order: 31 },
                { topic: "Articles with Places", order: 32 },
                { topic: "Frequency Expressions", order: 33 },
                { topic: "Obligation: Have to / Don't have to", order: 34 },
                { topic: "Should / Shouldn't for Advice", order: 35 },
                { topic: "Ordinal Numbers", order: 36 },
                { topic: "Describing People (Appearance)", order: 37 },
                { topic: "Describing People (Personality)", order: 38 },
                { topic: "Making Suggestions", order: 39 },
                { topic: "Present Perfect with Ever and Never", order: 40 }
            ],
            vocabulary: [
                { topic: "Food - Meals and Cooking", order: 1, wordCount: 20 },
                { topic: "Food - At the Restaurant", order: 2, wordCount: 20 },
                { topic: "Clothes and Accessories", order: 3, wordCount: 20 },
                { topic: "Shopping and Prices", order: 4, wordCount: 15 },
                { topic: "House and Rooms", order: 5, wordCount: 15 },
                { topic: "Furniture and Household Items", order: 6, wordCount: 20 },
                { topic: "Places in Town", order: 7, wordCount: 20 },
                { topic: "Directions", order: 8, wordCount: 15 },
                { topic: "Transport and Travel", order: 9, wordCount: 20 },
                { topic: "Weather and Seasons", order: 10, wordCount: 20 },
                { topic: "Hobbies and Free Time Activities", order: 11, wordCount: 25 },
                { topic: "Sports and Games", order: 12, wordCount: 20 },
                { topic: "Shopping Vocabulary", order: 13, wordCount: 20 },
                { topic: "Health Problems", order: 14, wordCount: 15 },
                { topic: "Parts of the Body", order: 15, wordCount: 20 },
                { topic: "Feelings and Emotions (Basic)", order: 16, wordCount: 15 },
                { topic: "Physical Appearance", order: 17, wordCount: 20 },
                { topic: "Personality Adjectives", order: 18, wordCount: 20 },
                { topic: "Daily Routine (Extended)", order: 19, wordCount: 20 },
                { topic: "Weekend Activities", order: 20, wordCount: 15 },
                { topic: "Holidays and Celebrations", order: 21, wordCount: 20 },
                { topic: "Technology - Basic Devices", order: 22, wordCount: 15 },
                { topic: "Technology - Internet and Communication", order: 23, wordCount: 15 },
                { topic: "Entertainment - TV and Films", order: 24, wordCount: 20 },
                { topic: "Entertainment - Music", order: 25, wordCount: 15 },
                { topic: "School and Education", order: 26, wordCount: 20 },
                { topic: "Work and Jobs (Extended)", order: 27, wordCount: 20 },
                { topic: "Time Expressions", order: 28, wordCount: 15 },
                { topic: "Describing Places", order: 29, wordCount: 20 },
                { topic: "Common Adjectives (Extended)", order: 30, wordCount: 25 }
            ]
        },

        B1: {
            grammar: [
                { topic: "Present Perfect Simple (Positive Forms)", order: 1 },
                { topic: "Present Perfect Simple (Negative Forms)", order: 2 },
                { topic: "Present Perfect Simple (Questions)", order: 3 },
                { topic: "Present Perfect with For and Since", order: 4 },
                { topic: "Present Perfect with Just, Already, Yet", order: 5 },
                { topic: "Present Perfect vs. Past Simple", order: 6 },
                { topic: "Past Continuous (Positive Forms)", order: 7 },
                { topic: "Past Continuous (Negative Forms and Questions)", order: 8 },
                { topic: "Past Simple vs. Past Continuous", order: 9 },
                { topic: "Used to for Past Habits", order: 10 },
                { topic: "Future with Will (Predictions)", order: 11 },
                { topic: "Future with Will (Decisions, Offers, Promises)", order: 12 },
                { topic: "Will vs. Going to", order: 13 },
                { topic: "First Conditional (If + Present Simple, Will)", order: 14 },
                { topic: "First Conditional (Unless, When, As Soon As)", order: 15 },
                { topic: "Modal Verbs - Should/Shouldn't", order: 16 },
                { topic: "Modal Verbs - Must/Mustn't", order: 17 },
                { topic: "Modal Verbs - Have to/Don't Have to", order: 18 },
                { topic: "Modal Verbs - Can/Could/May for Permission", order: 19 },
                { topic: "Modal Verbs - Might/May for Possibility", order: 20 },
                { topic: "Defining Relative Clauses (Who)", order: 21 },
                { topic: "Defining Relative Clauses (Which, That)", order: 22 },
                { topic: "Defining Relative Clauses (Where, When)", order: 23 },
                { topic: "Adverbs of Frequency (Extended)", order: 24 },
                { topic: "Adverbs of Manner (Extended)", order: 25 },
                { topic: "Comparative and Superlative Adverbs", order: 26 },
                { topic: "Gerunds after Prepositions", order: 27 },
                { topic: "Gerunds as Subjects and Objects", order: 28 },
                { topic: "Infinitives of Purpose", order: 29 },
                { topic: "Verb + Infinitive Patterns", order: 30 },
                { topic: "Verb + Gerund Patterns", order: 31 },
                { topic: "Verb + Infinitive or Gerund (Different Meanings)", order: 32 },
                { topic: "Zero Conditional", order: 33 },
                { topic: "Reported Speech - Statements", order: 34 },
                { topic: "Reported Speech - Questions", order: 35 },
                { topic: "Reported Speech - Commands", order: 36 },
                { topic: "Passive Voice - Present Simple", order: 37 },
                { topic: "Passive Voice - Past Simple", order: 38 },
                { topic: "Quantifiers (All, Most, Some, None, etc.)", order: 39 },
                { topic: "Articles (Advanced Usage)", order: 40 },
                { topic: "So and Such", order: 41 },
                { topic: "Both, Either, Neither", order: 42 },
                { topic: "Expressing Preferences", order: 43 },
                { topic: "Making Recommendations", order: 44 },
                { topic: "Expressing Opinions", order: 45 },
                { topic: "Too, Enough, Very, So", order: 46 },
                { topic: "Prepositions after Adjectives", order: 47 },
                { topic: "Prepositions after Verbs", order: 48 },
                { topic: "Present Perfect Continuous (Introduction)", order: 49 },
                { topic: "Question Tags", order: 50 }
            ],
            vocabulary: [
                { topic: "Work and Employment", order: 1, wordCount: 25 },
                { topic: "Job Responsibilities", order: 2, wordCount: 20 },
                { topic: "Workplace Vocabulary", order: 3, wordCount: 20 },
                { topic: "Education Systems", order: 4, wordCount: 20 },
                { topic: "School and University Subjects", order: 5, wordCount: 20 },
                { topic: "Learning and Studying", order: 6, wordCount: 20 },
                { topic: "Technology - Computers", order: 7, wordCount: 20 },
                { topic: "Technology - Mobile Devices", order: 8, wordCount: 20 },
                { topic: "Technology - Internet and Social Media", order: 9, wordCount: 25 },
                { topic: "Travel Arrangements", order: 10, wordCount: 25 },
                { topic: "Accommodation Types", order: 11, wordCount: 20 },
                { topic: "Holiday Activities", order: 12, wordCount: 20 },
                { topic: "Tourism and Sightseeing", order: 13, wordCount: 25 },
                { topic: "Environmental Issues", order: 14, wordCount: 25 },
                { topic: "Natural Features", order: 15, wordCount: 20 },
                { topic: "Weather Phenomena", order: 16, wordCount: 20 },
                { topic: "Feelings and Emotions (Advanced)", order: 17, wordCount: 25 },
                { topic: "Personal Qualities", order: 18, wordCount: 25 },
                { topic: "Relationships", order: 19, wordCount: 20 },
                { topic: "Sports Equipment and Venues", order: 20, wordCount: 20 },
                { topic: "Sports Events and Competitions", order: 21, wordCount: 20 },
                { topic: "Fitness and Exercise", order: 22, wordCount: 20 },
                { topic: "Entertainment - Cinema and Films", order: 23, wordCount: 25 },
                { topic: "Entertainment - Books and Reading", order: 24, wordCount: 20 },
                { topic: "Entertainment - Music and Concerts", order: 25, wordCount: 20 },
                { topic: "Media and News", order: 26, wordCount: 25 },
                { topic: "Food and Cooking Methods", order: 27, wordCount: 25 },
                { topic: "Restaurants and Eating Out", order: 28, wordCount: 20 },
                { topic: "Special Diets and Nutrition", order: 29, wordCount: 20 },
                { topic: "Common Phrasal Verbs (Group 1)", order: 30, wordCount: 20 },
                { topic: "Common Phrasal Verbs (Group 2)", order: 31, wordCount: 20 },
                { topic: "Common Collocations", order: 32, wordCount: 25 },
                { topic: "Health and Illness", order: 33, wordCount: 25 },
                { topic: "Medical Treatment", order: 34, wordCount: 20 },
                { topic: "City and Rural Life", order: 35, wordCount: 25 },
                { topic: "Housing and Accommodation", order: 36, wordCount: 20 },
                { topic: "Shopping and Consumer Issues", order: 37, wordCount: 25 },
                { topic: "Money and Banking", order: 38, wordCount: 20 },
                { topic: "Crime and Security", order: 39, wordCount: 25 },
                { topic: "Social Issues", order: 40, wordCount: 25 }
            ]
        },

        B2: {
            grammar: [
                { topic: "Present Perfect Continuous", order: 1 },
                { topic: "Present Perfect Simple vs. Continuous", order: 2 },
                { topic: "Past Perfect Simple", order: 3 },
                { topic: "Past Perfect vs. Past Simple", order: 4 },
                { topic: "Past Perfect Continuous", order: 5 },
                { topic: "Narrative Tenses (Review and Practice)", order: 6 },
                { topic: "Future Continuous", order: 7 },
                { topic: "Future Perfect", order: 8 },
                { topic: "Future Time Clauses", order: 9 },
                { topic: "Future in the Past", order: 10 },
                { topic: "Second Conditional (If + Past Simple, Would)", order: 11 },
                { topic: "Second Conditional (Other Modal Verbs)", order: 12 },
                { topic: "Third Conditional (If + Past Perfect, Would Have)", order: 13 },
                { topic: "Mixed Conditionals (Introduction)", order: 14 },
                { topic: "I Wish / If Only (Present)", order: 15 },
                { topic: "I Wish / If Only (Past)", order: 16 },
                { topic: "Passive Voice - Present Perfect", order: 17 },
                { topic: "Passive Voice - Future Forms", order: 18 },
                { topic: "Passive Voice - Modal Verbs", order: 19 },
                { topic: "Passive Voice with Two Objects", order: 20 },
                { topic: "Reported Speech - Tense Changes", order: 21 },
                { topic: "Reported Speech - Time and Place Changes", order: 22 },
                { topic: "Reported Speech - Reporting Verbs", order: 23 },
                { topic: "Defining and Non-defining Relative Clauses", order: 24 },
                { topic: "Relative Clauses with Prepositions", order: 25 },
                { topic: "Relative Clauses with Whose", order: 26 },
                { topic: "Omitting Relative Pronouns", order: 27 },
                { topic: "Modal Verbs of Deduction - Present (must, might, can't)", order: 28 },
                { topic: "Modal Verbs of Deduction - Past (must have, might have, can't have)", order: 29 },
                { topic: "Modal Verbs for Advice and Criticism", order: 30 },
                { topic: "Advanced Gerund and Infinitive Patterns", order: 31 },
                { topic: "Verbs with Gerund or Infinitive (Different Meanings)", order: 32 },
                { topic: "Perfect Infinitive and Gerund", order: 33 },
                { topic: "Causative Have and Get", order: 34 },
                { topic: "Advanced Passive Constructions", order: 35 },
                { topic: "Participle Clauses (Present and Past)", order: 36 },
                { topic: "Participle Clauses (Perfect)", order: 37 },
                { topic: "Inversion after Negative Adverbials", order: 38 },
                { topic: "Cleft Sentences (What, It)", order: 39 },
                { topic: "Emphasis with Auxiliary Verbs", order: 40 },
                { topic: "Unreal Past (as if, as though)", order: 41 },
                { topic: "Advanced Determiners (all, each, every, few, etc.)", order: 42 },
                { topic: "Adverb Placement", order: 43 },
                { topic: "Subjunctive Mood (Formal English)", order: 44 },
                { topic: "Future in the Past", order: 45 },
                { topic: "Advanced Noun Phrases", order: 46 },
                { topic: "Reduced Relative Clauses", order: 47 },
                { topic: "Ellipsis and Substitution", order: 48 },
                { topic: "Linking Words and Phrases", order: 49 },
                { topic: "Hedging Language", order: 50 },
                { topic: "Passive Reporting Structures", order: 51 },
                { topic: "Advanced Comparative Structures", order: 52 },
                { topic: "Future Perfect Continuous", order: 53 },
                { topic: "Hypothetical Meaning in the Past", order: 54 },
                { topic: "Modals of Obligation and Necessity (Review and Extension)", order: 55 }
            ],
            vocabulary: [
                { topic: "Business and Commerce", order: 1, wordCount: 30 },
                { topic: "Business Meetings", order: 2, wordCount: 25 },
                { topic: "Marketing and Advertising", order: 3, wordCount: 30 },
                { topic: "Finance and Investment", order: 4, wordCount: 30 },
                { topic: "Crime and Punishment", order: 5, wordCount: 30 },
                { topic: "Law and Justice", order: 6, wordCount: 25 },
                { topic: "Legal Terms", order: 7, wordCount: 25 },
                { topic: "Health and Fitness", order: 8, wordCount: 30 },
                { topic: "Medical Conditions", order: 9, wordCount: 30 },
                { topic: "Healthcare Systems", order: 10, wordCount: 25 },
                { topic: "Science and Research", order: 11, wordCount: 30 },
                { topic: "Technology and Innovation", order: 12, wordCount: 30 },
                { topic: "Scientific Discoveries", order: 13, wordCount: 25 },
                { topic: "Visual Arts", order: 14, wordCount: 25 },
                { topic: "Performing Arts", order: 15, wordCount: 25 },
                { topic: "Literature and Books", order: 16, wordCount: 30 },
                { topic: "Cultural Events and Traditions", order: 17, wordCount: 30 },
                { topic: "Politics and Government", order: 18, wordCount: 30 },
                { topic: "Elections and Voting", order: 19, wordCount: 25 },
                { topic: "International Relations", order: 20, wordCount: 25 },
                { topic: "Nature and Landscapes", order: 21, wordCount: 25 },
                { topic: "Wildlife and Conservation", order: 22, wordCount: 30 },
                { topic: "Environmental Protection", order: 23, wordCount: 30 },
                { topic: "Personality Traits", order: 24, wordCount: 30 },
                { topic: "Behavior and Attitudes", order: 25, wordCount: 30 },
                { topic: "Interpersonal Relationships", order: 26, wordCount: 25 },
                { topic: "Common Idioms (Group 1)", order: 27, wordCount: 25 },
                { topic: "Common Idioms (Group 2)", order: 28, wordCount: 25 },
                { topic: "Expressions and Sayings", order: 29, wordCount: 25 },
                { topic: "Advanced Phrasal Verbs (Group 1)", order: 30, wordCount: 30 },
                { topic: "Advanced Phrasal Verbs (Group 2)", order: 31, wordCount: 30 },
                { topic: "Collocations with Make and Do", order: 32, wordCount: 25 },
                { topic: "Collocations with Take and Get", order: 33, wordCount: 25 },
                { topic: "Word Formation - Prefixes", order: 34, wordCount: 25 },
                { topic: "Word Formation - Suffixes", order: 35, wordCount: 25 },
                { topic: "Education and Academic Language", order: 36, wordCount: 30 },
                { topic: "Media and Journalism", order: 37, wordCount: 30 },
                { topic: "Social Media and Digital Communication", order: 38, wordCount: 25 },
                { topic: "Urban Development", order: 39, wordCount: 25 },
                { topic: "Architecture and Design", order: 40, wordCount: 25 },
                { topic: "Travel and Tourism Industry", order: 41, wordCount: 30 },
                { topic: "Global Issues", order: 42, wordCount: 30 },
                { topic: "Work-Life Balance", order: 43, wordCount: 25 },
                { topic: "Career Development", order: 44, wordCount: 25 },
                { topic: "Formal and Informal Language", order: 45, wordCount: 30 }
            ]
        },

        C1: {
            grammar: [
                { topic: "Mixed Conditionals (Type 2/3)", order: 1 },
                { topic: "Mixed Conditionals (Type 3/2)", order: 2 },
                { topic: "Inverted Conditionals", order: 3 },
                { topic: "Implied Conditionals", order: 4 },
                { topic: "Advanced Passive Constructions with Reporting Verbs", order: 5 },
                { topic: "Advanced Passive with Infinitives and Gerunds", order: 6 },
                { topic: "Passive Voice for Emphasis and Focus", order: 7 },
                { topic: "Future in the Past (Advanced)", order: 8 },
                { topic: "Future Perfect Continuous", order: 9 },
                { topic: "Complex Future Time References", order: 10 },
                { topic: "Inversion with Negative Adverbials (Never, Rarely, etc.)", order: 11 },
                { topic: "Inversion for Emphasis", order: 12 },
                { topic: "Inversion in Conditional Sentences", order: 13 },
                { topic: "Present Participle Clauses", order: 14 },
                { topic: "Past Participle Clauses", order: 15 },
                { topic: "Perfect Participle Clauses", order: 16 },
                { topic: "Advanced Modal Verbs - Present Deduction", order: 17 },
                { topic: "Advanced Modal Verbs - Past Deduction", order: 18 },
                { topic: "Advanced Modal Verbs - Future Speculation", order: 19 },
                { topic: "Modal Perfect Forms (Should Have, Could Have, etc.)", order: 20 },
                { topic: "Cleft Sentences with It", order: 21 },
                { topic: "Cleft Sentences with What", order: 22 },
                { topic: "Cleft Sentences with All, The Thing, etc.", order: 23 },
                { topic: "Subjunctive in Formal Contexts", order: 24 },
                { topic: "Subjunctive in Fixed Expressions", order: 25 },
                { topic: "Unreal Uses of Past Tenses", order: 26 },
                { topic: "Ellipsis in Clauses", order: 27 },
                { topic: "Substitution (So, Not, etc.)", order: 28 },
                { topic: "Advanced Noun Phrases with Pre-modification", order: 29 },
                { topic: "Advanced Noun Phrases with Post-modification", order: 30 },
                { topic: "Complex Sentence Adverbials", order: 31 },
                { topic: "Fronting for Emphasis", order: 32 },
                { topic: "Advanced Reported Speech", order: 33 },
                { topic: "Reporting Verbs with Complex Patterns", order: 34 },
                { topic: "Hypothetical Past (Would Rather, It's Time)", order: 35 },
                { topic: "Advanced Verb Patterns", order: 36 },
                { topic: "Gerunds and Infinitives in Complex Structures", order: 37 },
                { topic: "Reduced Relative Clauses (Advanced)", order: 38 },
                { topic: "Nominal Relative Clauses", order: 39 },
                { topic: "Relative Clauses with Preposition Stranding", order: 40 },
                { topic: "Discourse Markers for Spoken English", order: 41 },
                { topic: "Discourse Markers for Written English", order: 42 },
                { topic: "Hedging Devices and Tentative Language", order: 43 },
                { topic: "Expressions of Concession", order: 44 },
                { topic: "Complex Coordination and Subordination", order: 45 },
                { topic: "Cohesive Devices for Extended Discourse", order: 46 },
                { topic: "Parallel Structures", order: 47 },
                { topic: "Emphatic Structures with Do/Does/Did", order: 48 },
                { topic: "Emphatic Reflexive Pronouns", order: 49 },
                { topic: "Sophisticated Conditionals", order: 50 },
                { topic: "Advanced Modality in Academic Writing", order: 51 },
                { topic: "Distancing Techniques", order: 52 },
                { topic: "Advanced Comparative and Superlative Forms", order: 53 },
                { topic: "Comparative Correlatives (The more... the more...)", order: 54 },
                { topic: "Adverbial Clauses of Contrast and Concession", order: 55 },
                { topic: "Adverbial Clauses of Purpose and Result", order: 56 },
                { topic: "Advanced Noun Complement Clauses", order: 57 },
                { topic: "Advanced Adjective Complement Clauses", order: 58 },
                { topic: "Parenthetical Structures", order: 59 },
                { topic: "Apposition", order: 60 }
            ],
            vocabulary: [
                { topic: "Academic Language and Research", order: 1, wordCount: 35 },
                { topic: "Academic Writing Style", order: 2, wordCount: 30 },
                { topic: "Academic Disciplines", order: 3, wordCount: 35 },
                { topic: "Business Negotiations", order: 4, wordCount: 35 },
                { topic: "Corporate Structure", order: 5, wordCount: 30 },
                { topic: "Economic Terms", order: 6, wordCount: 35 },
                { topic: "Financial Markets", order: 7, wordCount: 35 },
                { topic: "International Relations and Diplomacy", order: 8, wordCount: 35 },
                { topic: "Global Organizations", order: 9, wordCount: 30 },
                { topic: "International Conflicts", order: 10, wordCount: 30 },
                { topic: "Technology and Innovation (Advanced)", order: 11, wordCount: 35 },
                { topic: "Digital Transformation", order: 12, wordCount: 30 },
                { topic: "Artificial Intelligence", order: 13, wordCount: 35 },
                { topic: "Technological Trends", order: 14, wordCount: 35 },
                { topic: "Social Issues and Inequality", order: 15, wordCount: 35 },
                { topic: "Migration and Demographics", order: 16, wordCount: 30 },
                { topic: "Human Rights", order: 17, wordCount: 30 },
                { topic: "Ethics and Moral Dilemmas", order: 18, wordCount: 35 },
                { topic: "Philosophical Concepts", order: 19, wordCount: 35 },
                { topic: "Ethical Debates", order: 20, wordCount: 30 },
                { topic: "Advanced Idioms and Expressions (Group 1)", order: 21, wordCount: 35 },
                { topic: "Advanced Idioms and Expressions (Group 2)", order: 22, wordCount: 35 },
                { topic: "Idiomatic Comparisons", order: 23, wordCount: 30 },
                { topic: "Metaphors in Everyday Language", order: 24, wordCount: 35 },
                { topic: "Imagery and Symbolism", order: 25, wordCount: 30 },
                { topic: "Connotation and Denotation", order: 26, wordCount: 30 },
                { topic: "Formal Register", order: 27, wordCount: 35 },
                { topic: "Informal and Colloquial Language", order: 28, wordCount: 35 },
                { topic: "Register Shifts", order: 29, wordCount: 30 },
                { topic: "Nuanced Emotions and Attitudes", order: 30, wordCount: 35 },
                { topic: "Subtle Feelings and States", order: 31, wordCount: 35 },
                { topic: "Psychological Terms", order: 32, wordCount: 35 },
                { topic: "Advanced Phrasal Verbs (Group 3)", order: 33, wordCount: 35 },
                { topic: "Advanced Phrasal Verbs (Group 4)", order: 34, wordCount: 35 },
                { topic: "Multi-word Verbs", order: 35, wordCount: 30 },
                { topic: "Advanced Collocations (Group 1)", order: 36, wordCount: 35 },
                { topic: "Advanced Collocations (Group 2)", order: 37, wordCount: 35 },
                { topic: "Word Formation - Complex Forms", order: 38, wordCount: 30 },
                { topic: "Synonyms with Subtle Differences", order: 39, wordCount: 35 },
                { topic: "Near-synonyms and Precision", order: 40, wordCount: 35 },
                { topic: "Euphemisms and Politically Correct Language", order: 41, wordCount: 30 },
                { topic: "Media and Public Relations", order: 42, wordCount: 35 },
                { topic: "Cultural Identity and Diversity", order: 43, wordCount: 35 },
                { topic: "Arts and Aesthetics", order: 44, wordCount: 30 },
                { topic: "Literary Analysis", order: 45, wordCount: 35 }
            ]
        },

        C2: {
            grammar: [
                { topic: "Advanced Hypothetical Structures in Past, Present and Future", order: 1 },
                { topic: "Hypothetical Structures with Modal Perfects", order: 2 },
                { topic: "Remote Conditional Forms", order: 3 },
                { topic: "Conditional Structures without If", order: 4 },
                { topic: "Fronting for Cohesion and Emphasis", order: 5 },
                { topic: "Clefting for Information Structure", order: 6 },
                { topic: "Advanced Fronting Techniques", order: 7 },
                { topic: "Sophisticated Passive and Causative Forms", order: 8 },
                { topic: "Passive Infinitive Constructions", order: 9 },
                { topic: "Passive Gerund Constructions", order: 10 },
                { topic: "Subtle Distinctions in Modal Usage", order: 11 },
                { topic: "Modal Combinations", order: 12 },
                { topic: "Modality in Academic and Professional Discourse", order: 13 },
                { topic: "Advanced Noun Phrases with Multiple Modification", order: 14 },
                { topic: "Nominalisation for Academic and Formal Writing", order: 15 },
                { topic: "Complex Noun Phrases as Subjects", order: 16 },
                { topic: "Cohesion through Referencing", order: 17 },
                { topic: "Cohesion through Substitution and Ellipsis", order: 18 },
                { topic: "Cohesion through Lexical Devices", order: 19 },
                { topic: "Textual References and Deixis", order: 20 },
                { topic: "Advanced Inversion Patterns", order: 21 },
                { topic: "Inversion in Literary and Rhetorical Contexts", order: 22 },
                { topic: "Stylistic Inversion", order: 23 },
                { topic: "Sophisticated Conditionals with Modal Perfects", order: 24 },
                { topic: "Mixed Time References in Conditionals", order: 25 },
                { topic: "Implied and Abbreviated Conditionals", order: 26 },
                { topic: "Advanced Hedging Devices", order: 27 },
                { topic: "Hedging in Academic Writing", order: 28 },
                { topic: "Boosting and Emphasis Devices", order: 29 },
                { topic: "Rhetorical Questions", order: 30 },
                { topic: "Rhetorical Devices for Persuasion", order: 31 },
                { topic: "Rhetorical Devices for Emphasis", order: 32 },
                { topic: "Stylistic Variation - Formal Academic", order: 33 },
                { topic: "Stylistic Variation - Literary", order: 34 },
                { topic: "Stylistic Variation - Journalistic", order: 35 },
                { topic: "Complex Multi-clause Sentences", order: 36 },
                { topic: "Sentence Fragments for Effect", order: 37 },
                { topic: "Parenthetical Information", order: 38 },
                { topic: "Advanced Participle Constructions", order: 39 },
                { topic: "Participle Clauses with Advanced Time References", order: 40 },
                { topic: "Subjunctive in Advanced Contexts", order: 41 },
                { topic: "Alternatives to the Subjunctive", order: 42 },
                { topic: "Sophisticated Coordination", order: 43 },
                { topic: "Sophisticated Subordination", order: 44 },
                { topic: "Thematic Progression in Texts", order: 45 },
                { topic: "Information Structure and Focus", order: 46 },
                { topic: "Structural Parallelism", order: 47 },
                { topic: "Structural Repetition for Effect", order: 48 },
                { topic: "Sophisticated Reporting Structures", order: 49 },
                { topic: "Free Indirect Speech", order: 50 },
                { topic: "Advanced Comparative Structures", order: 51 },
                { topic: "Multiple Comparison", order: 52 },
                { topic: "Patterns of Concession and Contrast", order: 53 },
                { topic: "Patterns of Cause and Effect", order: 54 },
                { topic: "Metadiscourse Markers", order: 55 },
                { topic: "Evaluative Language", order: 56 },
                { topic: "Stance and Engagement Markers", order: 57 },
                { topic: "Subtle Expressions of Modality", order: 58 },
                { topic: "Subtle Expressions of Attitude", order: 59 },
                { topic: "Subtle Expressions of Evaluation", order: 60 },
                { topic: "Structural Ambiguity and Disambiguation", order: 61 },
                { topic: "Lexical Ambiguity and Disambiguation", order: 62 },
                { topic: "Pragmatic Markers", order: 63 },
                { topic: "Discourse Management", order: 64 },
                { topic: "Genre-specific Grammatical Features", order: 65 }
            ],
            vocabulary: [
                { topic: "Specialized Professional Terminology", order: 1, wordCount: 40 },
                { topic: "Legal Terminology", order: 2, wordCount: 40 },
                { topic: "Medical Terminology", order: 3, wordCount: 40 },
                { topic: "Scientific Research Terminology", order: 4, wordCount: 40 },
                { topic: "Business and Finance Jargon", order: 5, wordCount: 40 },
                { topic: "Academic Discourse Markers", order: 6, wordCount: 35 },
                { topic: "Academic Verbs for Research", order: 7, wordCount: 35 },
                { topic: "Academic Nouns for Concepts", order: 8, wordCount: 35 },
                { topic: "Diplomatic Language", order: 9, wordCount: 35 },
                { topic: "Political Discourse", order: 10, wordCount: 40 },
                { topic: "International Relations Terminology", order: 11, wordCount: 40 },
                { topic: "Cultural References in English-speaking Countries", order: 12, wordCount: 40 },
                { topic: "Literary Allusions", order: 13, wordCount: 35 },
                { topic: "Historical References", order: 14, wordCount: 35 },
                { topic: "Sophisticated Idiomatic Expressions (Group 1)", order: 15, wordCount: 40 },
                { topic: "Sophisticated Idiomatic Expressions (Group 2)", order: 16, wordCount: 40 },
                { topic: "Sophisticated Idiomatic Expressions (Group 3)", order: 17, wordCount: 40 },
                { topic: "Obscure Idioms and Expressions", order: 18, wordCount: 35 },
                { topic: "Connotations and Subtle Meanings", order: 19, wordCount: 40 },
                { topic: "Semantic Fields and Lexical Sets", order: 20, wordCount: 35 },
                { topic: "Nuanced Vocabulary for Opinions", order: 21, wordCount: 40 },
                { topic: "Nuanced Vocabulary for Arguments", order: 22, wordCount: 40 },
                { topic: "Nuanced Vocabulary for Description", order: 23, wordCount: 40 },
                { topic: "Humor, Irony, and Wordplay", order: 24, wordCount: 35 },
                { topic: "Puns and Double Meanings", order: 25, wordCount: 35 },
                { topic: "Sarcasm and Satire", order: 26, wordCount: 35 },
                { topic: "Archaic and Literary Language", order: 27, wordCount: 40 },
                { topic: "Neologisms and Contemporary Usage", order: 28, wordCount: 40 },
                { topic: "Slang and Colloquialisms", order: 29, wordCount: 40 },
                { topic: "Regional Variations of English", order: 30, wordCount: 40 },
                { topic: "British vs. American English", order: 31, wordCount: 40 },
                { topic: "Other English Varieties (Australian, Canadian, etc.)", order: 32, wordCount: 35 },
                { topic: "Advanced Phrasal Verbs (Group 5)", order: 33, wordCount: 40 },
                { topic: "Advanced Phrasal Verbs (Group 6)", order: 34, wordCount: 40 },
                { topic: "Rare and Specialized Phrasal Verbs", order: 35, wordCount: 35 },
                { topic: "Advanced Collocations (Group 3)", order: 36, wordCount: 40 },
                { topic: "Advanced Collocations (Group 4)", order: 37, wordCount: 40 },
                { topic: "Rare and Specialized Collocations", order: 38, wordCount: 35 },
                { topic: "Precise Synonyms and Near-synonyms", order: 39, wordCount: 40 },
                { topic: "Gradable and Non-gradable Adjectives", order: 40, wordCount: 35 },
                { topic: "Intensifiers with Gradable and Non-gradable Adjectives", order: 41, wordCount: 35 },
                { topic: "Philosophical and Abstract Concepts", order: 42, wordCount: 40 },
                { topic: "Ethical and Moral Terminology", order: 43, wordCount: 40 },
                { topic: "Advanced Technical Vocabulary", order: 44, wordCount: 40 },
                { topic: "Specialized Industry Terminology", order: 45, wordCount: 40 },
                { topic: "Advanced Media and Communication Terms", order: 46, wordCount: 40 },
                { topic: "Advanced Arts and Literature Terms", order: 47, wordCount: 40 },
                { topic: "Advanced Environmental and Sustainability Terms", order: 48, wordCount: 40 },
                { topic: "Advanced Psychology and Behavior Terms", order: 49, wordCount: 40 },
                { topic: "Advanced Social Sciences Terminology", order: 50, wordCount: 40 }
            ]
        }
    }
}